version: 0.0.2
plugins:
  location: ./plugins
  meta_only: false
download_folder:
  download: ./download/download
  temp: ./download/temp
  metadata: ./download/metadata
cache:
  enable: true
  folder: ./query_cache
delay:
  fetch: 25
  download: 25
max_size_batch: 25
max_parallel_fetch: 3
verbose: false
custom_downloader: false
request:
  _all:
    user_agent: mx-scraper/0.0.1 (windows; x86_64)
    headers:
      Accept: "*/*"
    cookies: null
  images:
    # headers and cookies inherit _all
    headers: {}
    # user_agent: ""
  # gallery-dl:
  #   extra_config:
  #     bin: D:\binaries\mx-scraper\gallery-dl.exe
