version: 0.0.2
plugins:
  location: ./plugins
  meta_only: false
download_folder:
  download: ./download/download
  temp: ./download/temp
  metadata: ./download/metadata
cache:
  enable: true
  folder: ./query_cache
delay:
  fetch: 25
  download: 25
max_size_batch: 25 # titles
max_size_init_crawl_batch: 3 # number of terms to process at init (metadata retrieval)
max_size_mini_batch: 3 # items in titles to process at a time (pages)
max_parallel_fetch: 100 # global fetch limit at a time (set high if target website does not whine much)
verbose: false
custom_downloader: false
http_client:
  use: default
  # use: flaresolverr
  # config:
  #   endpoint: http://localhost:8191/v1
  #   max_timeout: 60000
  #   session_ttl_minutes: 5 #rotate expired sessions
request:
  _all:
    user_agent: mx-scraper/0.0.1 (windows; x86_64)
    headers:
      Accept: "*/*"
    cookies: null
  images:
    # headers and cookies inherit _all
    headers: {}
    # user_agent: ""
  # gallery-dl:
  #   extra_config:
  #     bin: D:\binaries\mx-scraper\gallery-dl.exe
