version: 0.0.1
plugins:
  location: ./plugins
  meta_only: false
download_folder:
  download: ./download/download
  temp: ./download/temp
  metadata: ./download/metadata
cache:
  enable: true
  folder: ./query_cache
delay:
  fetch: 25
  download: 25
max_size_batch: 10
verbose: false
request:
  _all:
    headers: {}
    cookies: {}
  images:
    headers: {}
