version: 0.0.1
plugins:
  location: ./plugins
  meta_only: false
download_folder:
  download: ./download/download
  temp: ./download/temp
  metadata: ./download/metadata
cache:
  enable: true
  folder: ./query_cache
delay:
  fetch: 25
  download: 25
max_size_batch: 10
verbose: false
request:
  _all:
    user_agent: mx-scraper/0.0.1 (windows; x86_64)
    headers:
      Accept: '*/*'
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US,en;q=0.5
    cookies: null
  images:
    # headers and cookies inherit _all
    headers: {}
    # user_agent: ""
