# git tag
# git tag vx.y.z
# git push --tag

on:
 push:
   tags:
     - v*

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            extension: ""
          - os: windows-latest
            extension: ".exe"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Installing packages
        run: npm ci
        
      - name: Installing pkg cli
        run: npm install -g pkg

      - name: Building mx-scraper ${{ matrix.os }}
        run: node auto-build.js
        
      - name: Run mx-scraper --help
        run: ./bin/mx-scraper${{ matrix.extension }} --help

      - name: Run mx-scraper --infos
        run: |
          cd bin
          ./mx-scraper${{ matrix.extension }} --infos

      - name: Archive build for ${{ matrix.os }}
        run: |
          cd bin
          tar -czvf ../mx-scraper-${{ github.ref_name }}-${{ matrix.os }}.tar.gz *
      
      - name: Release ${{ matrix.os }}
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: "mx-scraper-${{ github.ref_name }}-${{ matrix.os }}.tar.gz"
          asset_name: "mx-scraper-${{ github.ref_name }}-${{ matrix.os }}.tar.gz"
          overwrite: true
