on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Installing packages
        run: npm ci
        
      - name: Installing pkg cli
        run: npm install -g pkg

      - name: Building mx-scraper
        run: node auto-build.js

      - name: Archive compiled build
        uses: actions/upload-artifact@v3
        with:
            name: mx-scraper-dist-folder
            path: bin/**/*
            retention-days: 30
