on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      flaresolverr:
        image: flaresolverr/flaresolverr
        ports:
          - 8191
        options: >-
          -p 8191:8191
          --cpus 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Installing packages
        run: npm ci
        
      - name: Transpiling
        run: npx tsc

      - name: Archive dist files
        uses: actions/upload-artifact@v3
        with:
            name: mx-scraper-dist-folder
            path: dist/**/*
            retention-days: 30

      - name: Test core algorithms
        run: npm test request core

      - name: Test plugin sample
        run: npm test gprincess

