name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        python3 -m pip install -U gallery-dl
        cargo build --verbose
    - name: Run tests
      run: |
        cargo install cargo-insta --version 1.15.0 --locked
        cargo test --verbose

